### ISSUE TITLE
Support multiple variables on LHS for varname.varname

### ISSUE THREAD

**Issue by EngHabu** [pwwang/python-varname#28] opened 2020-11-19 18:51 UTC
The code in [here](https://github.com/pwwang/python-varname/blob/master/varname.py#L243-L266) 
https://github.com/pwwang/python-varname/blob/6a1e8bd16a0ff498959d288d2059d394fc704800/varname.py#L243-L266

assumes the Node is a function call. There are other AST Node types. For example, the code below:

```
    class MyType(object):
        def __eq__(self, other):
            print(varname.nameof(self, caller=2))
            return super().__eq__(other)

    a = MyType()
    print(a == 3)
```

Throws an exception because The Node in this case is a `Compare Node` that doesn't have `args`. It does, however, have `n.left.id` to access the variable name we are calling `__eq__()` on.

**Comment by pwwang** [comment] 2020-11-19 19:35
What are you expecting this to output:
```python
print(varname.nameof(self, caller=2))
```
`"self"` or `"a"` ?

**Comment by EngHabu** [comment] 2020-11-19 19:36
`"a"`.. I'm not positive about the value passed in to `caller` (maybe 3?)

**Comment by pwwang** [comment] 2020-11-19 19:39
You should never use the `caller` argument in a direct `nameof` call, unless you are wrapping it in another function.
`nameof` is supposed to get the variable name right at that stack.

To get the instance name, I suggest you do this:

```python
    import varname

    class MyType(object):
        def __init__(self, *args, **kwargs):
            self.name = varname.varname()

        def __eq__(self, other):
            print(self.name)
            return super().__eq__(other)

    a = MyType()
    print(a == 3)
```

**Comment by EngHabu** [comment] 2020-11-19 19:56
My pattern is more like this:
```
    import varname

    class MyType(object):
        def __init__(self, *args, **kwargs):
            self.name = varname.varname(caller=3)

        def __eq__(self, other):
            print(f"name: {self.name}")
            return super().__eq__(other)

    def create_MyType():
        return MyType(), MyType()

    a, b = create_MyType()
    print(a == 3)
    print(b == 5)
```

Is there a way to get `a` and `b` here?

**Comment by alexmojaki** [comment] 2020-11-19 19:58
I think the use of `caller` is sensible, the intended behaviour is meant to be similar to this:

```python
import varname


class MyType(object):
    def __len__(self):
        print(varname.nameof(self, caller=2))
        return 3
    
a = MyType()
len(a)  # prints a
```

But the problem as *originally* stated is impossible. Consider this code:

```python
class MyType(object):
    def __eq__(self, other):
        print("eq")
        return True

a = MyType()
b = 3
a == b
b == a
```

There is no way to tell in `a == b` which name is calling `__eq__`.

**Comment by pwwang** [comment] 2020-11-19 20:11
@alexmojaki True. And `__len__` now is actually a wrapper for `nameof`

@EngHabu 
I see your point now. Now the problem is here:
https://github.com/pwwang/python-varname/blob/6a1e8bd16a0ff498959d288d2059d394fc704800/varname.py#L411-L424

instead of the fragment you attached initially. We only allow a `Name` or `Attribute` node currently.

Thinking about extending it into a `List`/`Tuple` of  `Name` or `Attribute` nodes.

**Comment by pwwang** [comment] 2020-11-19 20:14
@EngHabu 

If the above is implemented, are you satisfied with this?
```python
import varname

class MyType(object):
    def __init__(self, name, *args, **kwargs):
        self.name = name

    def __eq__(self, other):
        print(f"name: {self.name}")
        return super().__eq__(other)

def create_MyType():
    names = varname.varname()
    types = [MyType(name) for name in names]
    return types

a, b = create_MyType()
print(a == 3)
print(b == 5)
```

**Comment by alexmojaki** [comment] 2020-11-19 20:49
I like your idea @pwwang although I also agree with your assessment of the problem it raises.

The same thing can be done now with sorcery:

```python
import sorcery

class MyType(object):
    def __init__(self, name, *args, **kwargs):
        self.name = name

    def __eq__(self, other):
        print(f"name: {self.name}")
        return super().__eq__(other)

@sorcery.no_spells
def create_MyType():
    names = sorcery.assigned_names()
    types = [MyType(name) for name in names]
    return types

a, b = create_MyType()
print(a == 3)
print(b == 5)
```

@EngHabu does that solve your problem?

**Comment by pwwang** [comment] 2020-11-19 21:55
Link to commit: 2694c21968778fdd3f7ace3022e608e7c42ee960

How to use:
```
def func():
    return varname(nvars=None)

a = func() # a == 'a'
a, b = func() # (a, b) == ('a', 'b')
[a, b] = func() # (a, b) == ('a', 'b')

# limit the number of variables on LHS
def func():
    return varname(nvars=2)

a = func() # VarnameRetrievingError
a, b, c = func() # VarnameRetrievingError
a, b = func() # (a, b) == ('a', 'b')
```

In your case:

```
import varname

class MyType(object):
    def __init__(self, name, *args, **kwargs):
        self.name = name

    def __eq__(self, other):
        print(f"name: {self.name}")
        return super().__eq__(other)

def create_MyType():
    names = varname.varname(nvars=2)
    types = [MyType(name) for name in names]
    return types

a, b = create_MyType()
print(a == 3)
print(b == 5)
```

**Comment by pwwang** [comment] 2020-11-26 18:59
Closing this via v0.5.4
Now you can do:
```python
import varname

class MyType(object):
    def __init__(self, name, *args, **kwargs):
        self.name = name

    def __eq__(self, other):
        print(f"name: {self.name}")
        return super().__eq__(other)

def create_MyType():
    names = varname.varname(multi_vars=True)
    types = [MyType(name) for name in names]
    return types

a, b = create_MyType()
print(a == 3)
print(b == 5)
```

**Closed by pwwang** 2020-11-26 18:59 UTC
Labels: enhancement
