### ISSUE TITLE
Cannot get the var name of the var in a list.

### ISSUE THREAD

**Issue by Hzzone** [pwwang/python-varname#68] opened 2022-01-18 04:12 UTC
Thanks for your great job!

I am now using varname but found an strange thing is that we cannot get the var name of the var in a list. The code can be found below. If I use a piece of code from StackOverflow, all things look right.
```python
from varname import varname, nameof, will, argname
```

```python
a = 1
nameof(a) # 'a'
```

    'a'

```python
b = 3
c = 4
a = [b, c]
a
```

    [3, 4]

```python
import inspect
def get_varname(var):
    """
    Gets the name of var. Does it from the out most frame inner-wards.
    :param var: variable to get name from.
    :return: string
    """
    for fi in reversed(inspect.stack()):
        names = [var_name for var_name, var_val in fi.frame.f_locals.items() if var_val is var]
        if len(names) > 0:
            return names[0]
```

```python
get_varname(a[0])
```

    'b'

```python
nameof(a[0])
```

    ---------------------------------------------------------------------------

    ImproperUseError                          Traceback (most recent call last)

    <ipython-input-45-2ef558708817> in <module>
    ----> 1 nameof(a[0])
    

    ~/anaconda3/envs/sslearning/lib/python3.7/site-packages/varname/core.py in nameof(var, frame, vars_only, *more_vars)
        313         func=nameof,
        314         frame=frame,
    --> 315         vars_only=vars_only,
        316     )
        317     return out if more_vars else out[0]  # type: ignore

    ~/anaconda3/envs/sslearning/lib/python3.7/site-packages/varname/core.py in argname(arg, func, dispatch, frame, ignore, vars_only, *more_args)
        451         if isinstance(source, ast.AST):
        452             raise ImproperUseError(
    --> 453                 f"Argument {ast.dump(source)} is not a variable "
        454                 "or an attribute."
        455             )

    ImproperUseError: Argument Subscript(value=Name(id='a', ctx=Load()), slice=Index(value=Num(n=0)), ctx=Load()) is not a variable or an attribute.

It would be better if there exist some solutions.

**Comment by pwwang** [comment] 2022-01-18 06:27
The problem is that when we see `get_varname(a[0])`, there is no chance for us to trace `a = [b, c]`.

Using value to track the name cannot make sure that we get the correct name:

```python
>>> import inspect
>>> def get_varname(var):
...     """
...     Gets the name of var. Does it from the out most frame inner-wards.
...     :param var: variable to get name from.
...     :return: string
...     """
...     for fi in reversed(inspect.stack()):
...         names = [var_name for var_name, var_val in fi.frame.f_locals.items() if var_val is var]
...         if len(names) > 0:
...             return names[0]
...             
... 
>>> x = b = 3
>>> c = 4
>>> a = [b, c]
>>> 
>>> get_varname(a[0])
'x'
```

**Comment by pwwang** [comment] 2022-01-21 18:44
Closing this as it is out of scope.

**Closed by pwwang** 2022-01-21 18:44 UTC
